receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"

  # prometheus:
  #   endpoint: "0.0.0.0:8889"
  #   enable_open_metrics: true

  tempo:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

processors:
  batch:
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 10s

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]

