global:
  scrape_interval: 15s

scrape_configs:
- job_name: vm-host
  static_configs:
    - targets:
      - host.docker.internal:9100
- job_name: cadvisor
  static_configs:
    - targets:
      - cadvisor:8080