global:
  scrape_interval: 15s
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    instance: 'instance-1'

scrape_configs:
  - job_name: vm-host
    # optional labels (key value pair)
    # labels:
    #   group: 'production
    static_configs:
      - targets:
        - host.docker.internal:9100
  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080
  - job_name: otel_collector
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - otel-collector:8889