# https://grafana.com/docs/grafana/latest/administration/provisioning/

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    # Set to true if we want to enable prometheus exemplar
    # Exemplar config
    editable: true
    jsonData:
      httpMethod: GET
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: loki
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    uid: tempo
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true
        tags: [ {key: 'service.name', value: 'job'} ]